export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  RIGGING_SPACING_CONFLICT: "RIGGING_SPACING_CONFLICT",
  RIGGING_OVERWEIGHT: "RIGGING_OVERWEIGHT",
  RIGGING_DRAFT_RETAINED: "RIGGING_DRAFT_RETAINED"
} as const;
